services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_data:/var/lib/mysql"
      
volumes:
  mariadb_data
